### ISSUE TITLE
Support for Packer 0.7.0 and above

### ISSUE THREAD

**Issue by jasonlai** [sit/chef-packer#14]
Packer has changed its binary URL since version 0.7.0. The filename pattern specified in this cookbook doesn't support the latest Packer versions.

It would be great to have this fixed and made flexible to support versions below and above 0.7.0.

**Comment by kritesh** [comment]
packer installation fails while running  this step "cmd += " && rsync -a #{tmpdir}/#{strip_dir} #{new_resource.path}" under ark cookbook library.  I had to manually remove "#{strip_dir}". Installation went fine after that. Please fix this.

**Comment by jasonlai** [comment]
Thanks for reporting this. What version of `ark` do you use? Mine is `0.4.2`, which doesn't seem to have this `strip_dir` variable in `libraries/default.rb`. The file was (almost) the only one I see in the `ark` repo with rync related code you mentioned.

**Comment by thrashr888** [comment]
Seems like this guy's not going to merge this. I set the `version` to "packer_0.8.0" and it worked just fine, along with setting the `arch` and `checksum`.

**Comment by gsaslis** [comment]
+1 for merging this in..
