### ISSUE TITLE
Outdated dependency version on supermarket.chef.io

### ISSUE THREAD

**Issue by m1ndful** [sit/chef-packer#24]
Tried to install cookbook using Berkshelf and got strange conflict error. After some investigation I have found that cookbook conflicts with itself.
The issue is that dependencies specified in metadata.rb and supermarket.chef.io are different and makes conflict.

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [Unable to satisfy constraints on package ark due to solution constraint (packer = 0.3.0). Solution constraints that may result in a constraint on ark: [(packer = 0.3.0) -> (ark ~> 0.9.0)], [(packer = 0.3.0) -> (ark ~> 0.4.0)]
Demand that cannot be met: (packer = 0.3.0)
Artifacts for which there are conflicting dependencies: ark = 0.4.2 -> []Unable to find a solution for demands: packer (0.3.0)]
>>>>>> ----------------------
```

metadata.rb: `depends 'ark', '~> 0.9.0'`
supermarket.chef.io: ark ~> 0.4.0 [https://supermarket.chef.io/cookbooks/packer#dependencies]

**Comment by netflash** [comment]
This issue is outdated.
