### ISSUE TITLE
Mark cookbook as deprecated/abandoned

### ISSUE THREAD

**Issue by richid** [sit/chef-packer#25]
It's been a long time since this cookbook was updated and it's confusing as it's the first result listed in the Chef Supermarket. Please consider marking this as abandoned and directing people to use https://github.com/schubergphilis/sbp_packer

**Comment by netflash** [comment]
@richid @svanharmelen @KierranM hey guys, should we combine all the efforts to have one cookbook without duplicating features ?

**Comment by svanharmelen** [comment]
@Seth-Karlo guess your the better person to respond here?

**Comment by Seth-Karlo** [comment]
@netflash I'm happy to do that; are you reviving this cookbook or would you like to use ours?

**Comment by netflash** [comment]
@Seth-Karlo I'm not sure what would be better. Any thoughts ?
My thoughts: I have all the tools / accesses to revive this one. It works. Didn't assess your cookbook to understand the effort of merge all the possible extra features back here.

**Comment by Seth-Karlo** [comment]
@netflash Ours has some additional functionality but not much, it just allows for installation via source or via binary. As we have the ownership of ours, I propose making you a collaborator of ours and you marking this one as deprecated. Do you agree?

**Comment by netflash** [comment]
@Seth-Karlo sounds good.
As I'm a bit busy now - can you guys pull-request the deprecation message and maybe a tiny "How-To switch to `your` cookbook" with key differences ?
Appreciate that.
