### ISSUE TITLE
Berks install fails due to out of date ark dependency

### ISSUE THREAD

**Issue by amuresia** [sit/chef-packer#33]
When I am trying to berks vendor the dependencies for this cookbook, I get the following error:

- `ark (~> 1.1)` required by `packer-0.6.0`
- `ark (~> 2.0)` required by `terraform-1.0.2`

Is it possible to update the dependency in the metadata.rb without breaking the core functionality of this cookbook?

Thanks.

**Comment by netflash** [comment]
I don't use chef nowadays, so can't test it.
If you can create a pull-request to fix it - I'm happy to merge it.

**Comment by amuresia** [comment]
@netflash I wrote my own wrapper cookbook to address this as it was much quicker. I'll close the issue now.

Thank you!
